{"name": "Проверка c невалидным логином", "status": "passed", "description": "Пытаемся залогиниться в аккаунт пользователя, получаем ошибку 401", "start": 1725567289738, "stop": 1725567289946, "uuid": "dc97ebab-a998-4aca-8c54-82cfb1e3b5a7", "historyId": "163fbac4a50b86dea237f47a01dd012d", "testCaseId": "163fbac4a50b86dea237f47a01dd012d", "fullName": "tests.test_login_user.TestLoginUser#test_no_such_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-R6MANS9"}, {"name": "thread", "value": "42268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}